# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-integration-tests-linux-env-with-edge-capi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true
      - name: Install Tools
        run: |
          wget https://github.com/cloudfoundry/bosh-bootloader/releases/download/v8.4.110/bbl-v8.4.110_linux_x86-64 -P /tmp
          mv /tmp/bbl-* /usr/local/bin/bbl
          chmod +x /usr/local/bin/bbl
          bbl --version
          wget https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-7.0.1-linux-amd64 --output-document="/usr/local/bin/bosh"
          chmod +x /usr/local/bin/bosh
          bosh --version
          wget https://github.com/cloudfoundry/credhub-cli/releases/download/2.9.4/credhub-linux-2.9.4.tgz -P ~/
          tar xzvf ~/credhub-linux-2.9.4.tgz
          mv credhub /usr/local/bin/credhub
          chmod +x /usr/local/bin/credhub
          credhub --version
          rm ~/credhub-linux-2.9.4.tgz
      - name: Run Integration Tests
        run: |
          export CF_INT_PASSWORD="asdf"
          export CF_INT_OIDC_USERNAME="admin-oidc"
          export CF_INT_OIDC_PASSWORD="asdf"
          export CF_INT_API="https://api.ENV.cf-app.com"
          export CF_DIAL_TIMEOUT=15
          export CF_USERNAME=admin
          export FLAKE_ATTEMPTS=2
          export NODES=16
          ls -al
          go install github.com/onsi/ginkgo/ginkgo@v1.16.4
          
